#pragma once
 
#define __REPEAT_NMACRO_0(macro)
#define __REPEAT_NMACRO_1(macro) macro##_N(1)
#define __REPEAT_NMACRO_2(macro) macro##_N(2) __REPEAT_NMACRO_1(macro)
#define __REPEAT_NMACRO_3(macro) macro##_N(3) __REPEAT_NMACRO_2(macro)
#define __REPEAT_NMACRO_4(macro) macro##_N(4) __REPEAT_NMACRO_3(macro)
#define __REPEAT_NMACRO_5(macro) macro##_N(5) __REPEAT_NMACRO_4(macro)
#define __REPEAT_NMACRO_6(macro) macro##_N(6) __REPEAT_NMACRO_5(macro)
#define __REPEAT_NMACRO_7(macro) macro##_N(7) __REPEAT_NMACRO_6(macro)
#define __REPEAT_NMACRO_8(macro) macro##_N(8) __REPEAT_NMACRO_7(macro)
#define __REPEAT_NMACRO_9(macro) macro##_N(9) __REPEAT_NMACRO_8(macro)
#define __REPEAT_NMACRO_10(macro) macro##_N(10) __REPEAT_NMACRO_9(macro)
#define __REPEAT_NMACRO_11(macro) macro##_N(11) __REPEAT_NMACRO_0(macro)
#define __REPEAT_NMACRO_12(macro) macro##_N(12) __REPEAT_NMACRO_11(macro)
#define __REPEAT_NMACRO_13(macro) macro##_N(13) __REPEAT_NMACRO_12(macro)
#define __REPEAT_NMACRO_14(macro) macro##_N(14) __REPEAT_NMACRO_13(macro)
#define __REPEAT_NMACRO_15(macro) macro##_N(15) __REPEAT_NMACRO_14(macro)
#define __REPEAT_NMACRO_16(macro) macro##_N(16) __REPEAT_NMACRO_15(macro)
#define __REPEAT_NMACRO_17(macro) macro##_N(17) __REPEAT_NMACRO_16(macro)
#define __REPEAT_NMACRO_18(macro) macro##_N(18) __REPEAT_NMACRO_17(macro)
#define __REPEAT_NMACRO_19(macro) macro##_N(19) __REPEAT_NMACRO_18(macro)
#define __REPEAT_NMACRO_20(macro) macro##_N(20) __REPEAT_NMACRO_19(macro)
#define __REPEAT_NMACRO_21(macro) macro##_N(21) __REPEAT_NMACRO_20(macro)
#define __REPEAT_NMACRO_22(macro) macro##_N(22) __REPEAT_NMACRO_21(macro)
#define __REPEAT_NMACRO_23(macro) macro##_N(23) __REPEAT_NMACRO_22(macro)
#define __REPEAT_NMACRO_24(macro) macro##_N(24) __REPEAT_NMACRO_23(macro)
#define __REPEAT_NMACRO_25(macro) macro##_N(25) __REPEAT_NMACRO_24(macro)
#define __REPEAT_NMACRO_26(macro) macro##_N(26) __REPEAT_NMACRO_25(macro)
#define __REPEAT_NMACRO_27(macro) macro##_N(27) __REPEAT_NMACRO_26(macro)
#define __REPEAT_NMACRO_28(macro) macro##_N(28) __REPEAT_NMACRO_27(macro)
#define __REPEAT_NMACRO_29(macro) macro##_N(29) __REPEAT_NMACRO_28(macro)
#define __REPEAT_NMACRO_30(macro) macro##_N(30) __REPEAT_NMACRO_29(macro)
#define __REPEAT_NMACRO_31(macro) macro##_N(31) __REPEAT_NMACRO_30(macro)
#define __REPEAT_NMACRO_32(macro) macro##_N(32) __REPEAT_NMACRO_31(macro)
#define REPEAT_NMACRO(macro,N) __REPEAT_NMACRO_##N(macro)
